In [2]:
import numpy as np

In [4]:
lista = [1,2,3,4,5,6,7,8,9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
arr = np.array(lista)

In [6]:
type(arr)

numpy.ndarray

In [7]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
arr[-3:]

array([7, 8, 9])

In [11]:
matriz[1:,0:2]

array([[4, 5],
       [7, 8]])

In [15]:
matriz3 = [[[1,2,3],[4,5,6],[7,8,9]],[[5,8,4],[9,2,7],[3,7,0]]]
matriz3 = np.array(matriz)

In [16]:
matriz3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[5, 8, 4],
        [9, 2, 7],
        [3, 7, 0]]])

In [26]:
matriz3[0,:2,:2]

array([[1, 2],
       [4, 5]])