In [1]:
import numpy as np

In [2]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [4]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [8]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
np.random.rand()

0.9483333240299467

In [14]:
np.random.rand(4)

array([0.96822517, 0.94350848, 0.89268805, 0.79380038])

In [15]:
np.random.rand(4,4)

array([[0.9797131 , 0.61647897, 0.28701373, 0.85050729],
       [0.10212262, 0.02243815, 0.12644811, 0.39483711],
       [0.53276688, 0.17979628, 0.55989849, 0.86391458],
       [0.62510307, 0.05552123, 0.54253339, 0.15241442]])

In [16]:
np.random.randint(1,15)

10

In [17]:
np.random.randint(1,100,(10,10))

array([[84, 65, 94, 95, 96, 67, 72, 51,  6, 82],
       [17, 64, 78, 68, 48, 86, 89, 58, 69, 69],
       [47, 81, 54, 88, 36, 55, 60, 93, 43, 38],
       [65, 65, 11, 22, 44, 95, 46, 58, 83, 68],
       [28, 64, 80, 79, 60, 74, 78, 13, 77, 78],
       [43, 34, 23, 71, 99,  7, 87, 92, 32, 85],
       [11, 57, 91, 50, 17, 69, 68,  7, 26, 71],
       [25, 50, 20, 63, 65, 15, 19, 86, 50, 53],
       [44, 16, 39, 96, 65, 38, 99, 84,  8, 13],
       [24, 79, 98, 94, 61, 25, 13,  2, 72, 71]])