In [2]:
import numpy as np

In [4]:
arr = np.random.randint(1,20,10)
arr

array([14, 19,  9, 14, 18,  2,  7, 17,  7,  6])

In [5]:
matriz = arr.reshape(2,5)
matriz

array([[14, 19,  9, 14, 18],
       [ 2,  7, 17,  7,  6]])

In [6]:
arr.max()

19

In [7]:
matriz.max()

19

In [8]:
matriz.max(0)

array([14, 19, 17, 14, 18])

In [9]:
arr.argmax()

1

In [10]:
matriz.argmax(0)

array([0, 0, 1, 0, 0], dtype=int64)

In [11]:
arr.min()

2

In [12]:
matriz.min(0)

array([2, 7, 9, 7, 6])

In [13]:
arr.argmin()

5

In [14]:
matriz.argmin(1)

array([2, 0], dtype=int64)

In [15]:
arr

array([14, 19,  9, 14, 18,  2,  7, 17,  7,  6])

Podemos saber la distancia entre el valor más bajo con el más alto.

In [16]:
arr.ptp()

17

In [17]:
matriz.ptp(1)

array([10, 15])

In [18]:
arr.sort()
arr

array([ 2,  6,  7,  7,  9, 14, 14, 17, 18, 19])

In [19]:
np.percentile(arr,50)

11.5

In [20]:
np.median(arr)

11.5

In [21]:
np.median(matriz,1)

array([ 7., 17.])

Desviacion estandar

In [22]:
np.std(arr) ** 2

30.810000000000002

In [23]:
np.var(arr)

30.810000000000002

media o promedio

In [24]:
np.mean(arr)

11.3

In [37]:
a = np.array([[1,2],[3,4]])
b = np.array([5,6])

In [28]:
np.concatenate((a,b),axis=0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [38]:
a.ndim
b.ndim

1

In [39]:
b = np.expand_dims(b,axis=0)
b

array([[5, 6]])

In [40]:
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [41]:
np.concatenate((a,b),axis=1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

Como ‘b’ es una fila y no una columna, no se puede concatenar a menos que se aplique la transpuesta.

In [42]:
np.concatenate((a,b.T),axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

La transpuesta pone nuestro array en sentido opuesto, si el array original es (1,2), con la transpuesta quedará (2,1)

In [43]:
b.T

array([[5],
       [6]])