In [1]:
import numpy as np

In [2]:
lista = [1,2]
lista

[1, 2]

In [3]:
lista * 2

[1, 2, 1, 2]

In [5]:
arr = np.arange(0,10)
arr2 = arr.copy()

Operaciones

In [6]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
arr + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [9]:
1 / arr

C:\Users\VALENCIA\AppData\Local\Temp\ipykernel_6772\1528351372.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [10]:
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [11]:
arr + arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
arr * arr2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [14]:
matriz  = arr.reshape(2,5)
matriz2 = matriz.copy()

In [15]:
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [16]:
matriz + matriz2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [18]:
matriz2.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

Una operación importante es la de punto por punto, aquí dos formas de hacerla:

In [19]:
np.matmul(matriz,matriz2.T)

array([[ 30,  80],
       [ 80, 255]])

In [20]:
matriz @ matriz2.T

array([[ 30,  80],
       [ 80, 255]])

# Unique

In [23]:
arr_dupl = np.array([11,11,12,13,13,15,15,17,12,13,11,14,19])
arr_dupl

array([11, 11, 12, 13, 13, 15, 15, 17, 12, 13, 11, 14, 19])

In [24]:
unique = np.unique(arr_dupl)
unique

array([11, 12, 13, 14, 15, 17, 19])

In [25]:
unique, ocurrence = np.unique(arr_dupl,return_counts=True)
print(unique)
ocurrence

[11 12 13 14 15 17 19]


array([3, 2, 3, 1, 2, 1, 1], dtype=int64)