In [1]:
import numpy as np

In [3]:
arr = np.random.randint(1,10,(3,2))

In [5]:
arr.shape

(3, 2)

In [6]:
arr

array([[6, 2],
       [7, 6],
       [5, 9]])

In [7]:
arr.reshape(1,6)

array([[6, 2, 7, 6, 5, 9]])

In [8]:
arr.reshape(2,3)

array([[6, 2, 7],
       [6, 5, 9]])

In [9]:
np.reshape(arr,(1,6))

array([[6, 2, 7, 6, 5, 9]])

In [10]:
arr

array([[6, 2],
       [7, 6],
       [5, 9]])

In [11]:
np.reshape(arr,(2,3),'C')

array([[6, 2, 7],
       [6, 5, 9]])

Se puede hacer reshape a como lo haría Fortran.

In [12]:
np.reshape(arr,(2,3),'F')

array([[6, 5, 6],
       [7, 2, 9]])

existe la opción de hacer reshape según como esté optimizado nuestro computador. En este caso es como en C.

In [13]:
np.reshape(arr,(2,3),'A')

array([[6, 2, 7],
       [6, 5, 9]])

No puedes cambiar la "forma" a la "forma" original del array, si tienes un (3,3) no lo puedes pasar a (4,2). 
No respeta los 9 elementos del array original