In [2]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4])
arr.dtype

dtype('int32')

In [3]:
arr = np.array([1,2,3,4], dtype='float64')
arr.dtype

dtype('float64')

In [4]:
arr

array([1., 2., 3., 4.])

In [6]:
arr = np.array([1,0,3,4])
arr = arr.astype(np.bool_)
arr

array([ True, False,  True,  True])

In [7]:
arr = np.array([1,0,3,4])
arr = arr.astype(np.string_)
arr

array([b'1', b'0', b'3', b'4'], dtype='|S11')

In [8]:
arr = np.array(['1','0','3','4'])
arr = arr.astype(np.int8)
arr

array([1, 0, 3, 4], dtype=int8)

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.array(['hola','2','4','5'],dtype='float64')

ValueError: could not convert string to float: 'hola'